export const Campus = [
  { value: "Abia State University", label: "ABSU" },
  { value: "Abubakar Tafawa Balewa University", label: "ATBU" },
  { value: "Achievers University, Owo", label: "AUO" },
  { value: "Adamawa State University", label: "ADSU" },
  { value: "Adekunle Ajasin University", label: "AAUA" },
  { value: "Adeleke University", label: "AU" },
  { value: "Afe Babalola University", label: "ABUAD" },
  { value: "Ahmadu Bello University", label: "ABU" },
  { value: "Ajayi Crowther University", label: "ACU" },
  { value: "Akwa Ibom State University", label: "AKSU" },
  { value: "Al-Hikmah University", label: "Al-Hikmah" },
  { value: "Al-Qalam University, Katsina", label: "AUK" },
  { value: "Ambrose Alli University", label: "AAU" },
  { value: "American University of Nigeria", label: "AUN" },
  { value: "Babcock University", label: "BABCOCK" },
  { value: "Bauchi State University", label: "BASU" },
  { value: "Bayero University Kano", label: "BUK" },
  { value: "Baze University", label: "Baze" },
  { value: "Bells University of Technology", label: "Bellstech" },
  { value: "Benson Idahosa University", label: "BIU" },
  { value: "Benue State University", label: "BSU" },
  { value: "Bingham University", label: "Bingham" },
  { value: "Borno State University", label: "BOSU" },
  { value: "Bowen University", label: "BU" },
  { value: "Caleb University", label: "Caleb" },
  { value: "Caritas University", label: "Caritas" },
  { value: "Chrisland University", label: "Chrisland" },
  { value: "Chukwuemeka Odumegwu Ojukwu University", label: "COOU" },
  { value: "Clifford University", label: "Clifford" },
  { value: "Coal City University", label: "CCU" },
  { value: "Covenant University", label: "CU" },
  { value: "Crawford University", label: "Crawford" },
  { value: "Crescent University, Abeokuta", label: "CUAB" },
  { value: "Cross River University of Technology", label: "CRUTECH" },
  { value: "Crown Hill University", label: "Crown Hill" },
  { value: "Delta State University, Abraka", label: "DELSU" },
  { value: "Dominican University, Ibadan", label: "Dominican" },
  { value: "Eastern Palm University", label: "EPU" },
  { value: "Ebonyi State University", label: "EBSU" },
  { value: "Edo University", label: "EUI" },
  { value: "Edwin Clark University", label: "ECU" },
  { value: "Ekiti State University, Ado Ekiti", label: "EKSU" },
  {
    value: "Eko University of Medical and Health Sciences",
    label: "EkoUNIMED",
  },
  { value: "Elizade University", label: "Elizade" },
  { value: "Enugu State University of Science and Technology", label: "ESUT" },
  { value: "Evangel University Akaeze", label: "EUA" },
  { value: "Federal University of Agriculture, Abeokuta", label: "FUNAAB" },
  { value: "Federal University of Petroleum Resources", label: "FUPRE" },
  { value: "Federal University of Technology, Akure", label: "FUTA" },
  { value: "Federal University of Technology, Minna", label: "FUTMINNA" },
  { value: "Federal University of Technology, Owerri", label: "FUTO" },
  { value: "Federal University, Birnin Kebbi", label: "FUBK" },
  { value: "Federal University, Dutse", label: "FUD" },
  { value: "Federal University, Dutsin-Ma", label: "FUDMA" },
  { value: "Federal University, Gashua", label: "FUGASHUA" },
  { value: "Federal University, Gusau", label: "FUGUS" },
  { value: "Federal University, Kashere", label: "FUKASHERE" },
  { value: "Federal University, Lafia", label: "FULAFIA" },
  { value: "Federal University, Lokoja", label: "FULOKOJA" },
  { value: "Federal University, Ndufu-Alike", label: "FUNAI" },
  { value: "Federal University, Otuoke", label: "FUOTUOKE" },
  { value: "Federal University, Oye-Ekiti", label: "FUOYE" },
  { value: "Federal University, Wukari", label: "FUWUKARI" },
  { value: "Fountain University", label: "Fountain" },
  { value: "Gombe State University", label: "GSU" },
  { value: "Gombe State University of Science and Technology", label: "GSUST" },
  { value: "Ibrahim Badamasi Babangida University", label: "IBBU" },
  { value: "Igbinedion University Okada", label: "IUO" },
  { value: "Imo State University", label: "IMSU" },
  { value: "Kaduna State University", label: "KASU" },
  { value: "Kano University of Science and Technology", label: "KUST" },
  {
    value: "Kebbi State University of Science and Technology",
    label: "KSUSTA",
  },
  { value: "Kings University", label: "Kings" },
  { value: "Kogi State University", label: "KSU" },
  { value: "Kwara State University", label: "KWASU" },
  { value: "Ladoke Akintola University of Technology", label: "LAUTECH" },
  { value: "Lagos State University", label: "LASU" },
  { value: "Landmark University", label: "Landmark" },
  { value: "Lead City University", label: "LCU" },
  { value: "Madonna University, Okija", label: "Madonna" },
  { value: "Nasarawa State University", label: "NSUK" },
  { value: "Niger Delta University", label: "NDU" },
  { value: "Nile University of Nigeria", label: "Nile" },
  { value: "Nnamdi Azikiwe University", label: "UNIZIK" },
  { value: "Northwest University Kano", label: "NWU" },
  { value: "Obafemi Awolowo University", label: "OAU" },
  {
    value: "Ondo State University of Science and Technology",
    label: "OSUSTECH",
  },
  { value: "Osun State University", label: "UNIOSUN" },
  { value: "Pan African University", label: "PAU" },
  { value: "Plateau State University", label: "PLASU" },
  { value: "Redeemer's University", label: "RUN" },
  {
    value: "Rivers State University of Science and Technology",
    label: "RSUST",
  },
  { value: "Sokoto State University", label: "SSU" },
  { value: "Taraba State University", label: "TASU" },
  { value: "Umaru Musa Yar'Adua University", label: "UMYU" },
  { value: "University of Abuja", label: "UNIABUJA" },
  { value: "University of Africa", label: "UAT" },
  { value: "University of Agriculture, Makurdi", label: "FUAM" },
  { value: "University of Benin", label: "UNIBEN" },
  { value: "University of Calabar", label: "UNICAL" },
  { value: "University of Ibadan", label: "UI" },
  { value: "University of Ilorin", label: "UNILORIN" },
  { value: "University of Jos", label: "UNIJOS" },
  { value: "University of Lagos", label: "UNILAG" },
  { value: "University of Maiduguri", label: "UNIMAID" },
  { value: "University of Medical Sciences", label: "UNIMED" },
  { value: "University of Nigeria", label: "UNN" },
  { value: "University of Port Harcourt", label: "UNIPORT" },
  { value: "University of Uyo", label: "UNIUYO" },
  { value: "Usmanu Danfodio University", label: "UDUSOK" },
  { value: "Veritas University", label: "Veritas" },
  { value: "Western Delta University", label: "WDU" },
  { value: "Yobe State University", label: "YSU" },
];
