export { default as BuyerDashboard } from "./Buyer/Dashboard/dashboard";
export { default as SellerDashboard } from "./Seller/Dashboard/dashboard";
export { default as SellerProducts } from "./Seller/Products/Products";
export { default as NewSellerProduct } from "./Seller/Products/New";
export { default as AddNewProducts } from "./Seller/Products/New/CreateNew";
export { default as SellerPayment } from "./Seller/Payment/Payment";
export { default as PaymentRegScreen } from "./Seller/Payment/RegistrationScreen";
export { default as Cart } from "./Buyer/Cart/Cart";
export { default as SellerProfile } from "./Seller/Profile/profile";
export { default as CreateStore } from "./Seller/Dashboard/CreateStore/CreateStore"