export {default as appleStoreImg} from "./applestore.png"
export { default as googlePlayImg } from "./googleplay.png";
export { default as marketLogo } from "./market.png";
export { default as registerImg } from "./register.png";
export { default as phone } from "./phone.png";
export { default as watch } from "./watch.png";
export { default as headset } from "./headset.png";
export { default as wallet } from "./wallet.png";
export { default as cloth } from "./cloth.jpg";
export { default as logo } from "./logo.png";
export { default as banner } from './banner.png'
export { default as image202 } from './image102.png'
export { default as image26 } from './image26.png'
export { default as image104 } from './image104.png'
export { default as userPic } from './userpic.jpg'
export { default as color1 } from './color1.png'
export { default as color2 } from './color2.png'
export { default as rotate3d } from './3d-rotate.svg';
export { default as square3d } from './3d-square.svg';
export { default as group } from './group.svg';
export { default as image34 } from './image34.png';
export { default as check } from './check.svg';
export { default as amexpress } from './amexpresspayment.png';
export { default as applepay } from './applepayment.png';
export { default as masterpay } from './masterpayment.png';
export { default as paypal } from './paypalpayment.png';
export { default as visa } from './visapayment.png';
export { default as arike } from './Arike-background.png';
export { default as profileAdd } from './profile-add.svg';
export { default as message } from './message.svg';
export { default as report } from './report.svg';
export { default as location } from './location-add.png'
export { default as dashboard } from './dashboard.svg';
export { default as emptyWallet } from './empty-wallet-tick.svg';
export { default as documentText } from './document-text.svg';
export { default as sendSquare } from './send-sqaure-2.svg';
export { default as settings } from './setting-2.svg';
export { default as shop } from './shop.svg';
export { default as shoppingCart } from './shopping-cart.svg';
export { default as userTag } from './user-tag.svg';
export { default as dashboardUnfilled } from './category.svg';
export { default as emptyWalletUnfilled } from './empty-wallet-tick-unfilled.svg';
export { default as documentTextUnfilled } from './document-text-unfilled.svg';
export { default as settingsUnfilled } from './setting-2-unfilled.svg';
export { default as shopUnfilled } from './shop-unfilled.svg';
export { default as shoppingCartUnfilled } from './shopping-cart-unfilled.svg';
export { default as userTagUnfilled } from './user-tag-unfilled.svg';
export { default as messageEdit } from './message-edit.svg';
export { default as shopWhite } from './shop-white.svg'